services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: imgpot
      POSTGRES_USER: imgpot
      POSTGRES_PASSWORD: imgpot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
