service: imgpot
image: herrkris/imgpot

servers:
  web:
    hosts:
      - 91.99.74.154

proxy:
  ssl: true
  host: imgpot.de
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    
registry:
  server: ghcr.io
  username: herrkris
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - DATABASE_URL
    - BUNNY_STORAGE_ZONE
    - BUNNY_STORAGE_API_KEY
    - BUNNY_STORAGE_REGION
    - BUNNY_CDN_HOSTNAME
    - SESSION_SECRET

builder:
  arch: arm64

ssh:
  user: imgpot
  port: 2222

accessories:
  db:
    image: postgres:17-alpine
    host: 91.99.74.154
    port: "127.0.0.1:5432:5432"
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    directories:
      - data:/var/lib/postgresql/data
