service: imgpot
image: herrkris/imgpot

servers:
  web:
    hosts:
      - 91.99.74.154

proxy:
  ssl: true
  host: imgpot.de
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    
registry:
  server: ghcr.io
  username: herrkris
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    BODY_SIZE_LIMIT: "25M"
    CORS_ALLOWED_ORIGINS: "http://localhost:4200,https://potber.de,https://test.potber.de,https://*.preview.potber.de"
    POTBER_AUTH_BASE: "https://auth.potber.de"
    POTBER_API_BASE: "https://api.potber.de"
  secret:
    - BUNNY_DATABASE_URL
    - BUNNY_DATABASE_AUTH_TOKEN
    - BUNNY_STORAGE_ZONE
    - BUNNY_STORAGE_API_KEY
    - BUNNY_STORAGE_REGION
    - BUNNY_CDN_HOSTNAME
    - SESSION_SECRET
    

builder:
  arch: arm64

ssh:
  user: imgpot
  port: 2222
